#!/usr/bin/env node
/**
 * 嵌入客户端构建产物为 JS 模块
 *
 * 读取 client/dist/ 所有静态文件，生成 server/dist/embedded-client.js
 * 用于 SEA 二进制场景，无需文件系统路径即可提供前端静态文件
 *
 * 用法: node scripts/embed-client.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const clientDist = path.resolve(root, '..', 'client', 'dist');
const outputFile = path.resolve(root, 'dist', 'embedded-client.js');

const MIME_TYPES = {
  '.html':   'text/html; charset=utf-8',
  '.js':     'text/javascript; charset=utf-8',
  '.css':    'text/css; charset=utf-8',
  '.svg':    'image/svg+xml',
  '.png':    'image/png',
  '.ico':    'image/x-icon',
  '.json':   'application/json',
  '.woff2':  'font/woff2',
  '.woff':   'font/woff',
  '.ttf':    'font/ttf',
  '.webp':   'image/webp',
  '.map':    'application/json',
};

if (!fs.existsSync(clientDist)) {
  console.error(`❌ Client dist not found: ${clientDist}`);
  console.error('   Run "pnpm build" in the client directory first.');
  process.exit(1);
}

// 递归收集所有文件
const files = [];
function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else {
      const rel = path.relative(clientDist, full).replace(/\\/g, '/');
      const ext = path.extname(rel);
      const content = fs.readFileSync(full);
      files.push({
        path: '/' + rel,
        content: content.toString('base64'),
        mime: MIME_TYPES[ext] || 'application/octet-stream',
      });
    }
  }
}
walk(clientDist);

// 生成 JS module 代码
const lines = [
  '// Auto-generated by embed-client.mjs — DO NOT EDIT',
  '// Source: client/dist/',
  `// Generated: ${new Date().toISOString()}`,
  `// Total files: ${files.length}`,
  '',
  '/** @type {Object<string, { content: Buffer, mimeType: string }>} */',
  'const files = {',
];

for (const f of files) {
  lines.push(`  "${f.path}": { content: Buffer.from("${f.content}", "base64"), mimeType: "${f.mime}" },`);
}
lines.push('};');
lines.push('');
lines.push('module.exports = files;');
lines.push('');

// 确保输出目录存在
const outputDir = path.dirname(outputFile);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputFile, lines.join('\n'), 'utf-8');
console.log(`✅ Embedded ${files.length} client files into ${path.relative(root, outputFile)}`);