name: Telegram Release Notifier

on:
  release:
    types: [published, prereleased]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send release notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: 14
          parse_mode: "HTML"
          message: |
            <b>${{ github.event.release.prerelease && '🚧 预发布版本' || '🎉 正式版本发布' }}</b>
            <i>${{ github.repository }}</i>
            
            <b>🔖 版本标签：</b>
            <code>${{ github.event.release.tag_name }}</code>
            
            <b>📄 发布标题：</b>
            ${{ github.event.release.name }}
            
            <b>📝 更新日志：</b>
            <pre>${{ format('{0}', github.event.release.body || '无详细描述') }}</pre>
            
            <b>🔗 链接：</b>
            <a href="${{ github.event.release.html_url }}">GitHub Release 页面</a>
            
            <b>📅 发布时间：</b>
            ${{ fromJSON(format('"{0}"', github.event.release.published_at)) }}